language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11
script:
- "./gradlew build"
deploy:
  provider: heroku
  app: rs-order-api
  api_key:
    secure: cP+UYVrN/7nvC4YVprrHVukXld1AP4pgHimaLoP2hkAvjtBtsw5ltJnieeqOZtijvGZSD9zYvnb6bo5QYRLgpdP4N+AfL3Poe/YB2yGFbxrWu+XG0l5OERovBeKBVt16q0+jRnv7tXnIikRzFvytYJswBjxJRR793axH1OSC6bheX7PKugH6sToU8oMxYEHvpBKwn/63iywtJgv2uxUOC3PFs+HtpxTmFJd/6ZBAPG0gsdNYDaCsqSDJoc6I4Cs26tC/gzMhoiPMA5lIPUyLYQozLMPfxC3Zw3oEecgBdismYgVHoEZbS59DZ2MvFqDmWmIiWKQQiz2UtTmIdzHH6E5BArUAJTJ6xXYEx1SftMLFY8OIm+eClQV31bW8MuaIfllhQcEsC0U2k9cTPhCvkYdmd8/PsIwI1GSu+7On/NmE7ZA4x6m+hpiLocBC65//chjW1pAFvTIBZuH2ZChxPysvsZvQPVKXf8C4QGdTDpCqC5jkxM2tUI/XZB0C2l1EVEBl8WRdJEnjMC9nzpB5sHPPGTZesKRmWHkBcEJiwhHbsJmCIkPMkuN0BSjebjL0m8icW65WrtxNPPnytaal1UqO88VoK2gaTLfjuyWxdXpU5lqA3avEK96AfZTtGpXKBczEnlYdYxYVtWSl3Q1groJIArENyZlOBfiSLmisTXI=
